### ISSUE TITLE
Data available?

### ISSUE THREAD

**Issue by ahmad-ra** [drhuangliwei/DAN-SNR#2]
Hello. Is it available that you provide the csv input data files? I don't see them available in any branch.

**Comment by drhuangliwei** [comment]
No problem
















At 2021-03-10 05:53:31, "ahmad-ra" ***@***.***> wrote:

Hello. Is it available that you provide the csv input data files? I don't see them available in any branch.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的超大附件
data - 复件.rar (64.6M, 2021年3月30日 19:59 到期)
下载

**Comment by ahmad-ra** [comment]
I believe this is the attachment for the data right? ( 从网易163邮箱发来的超大附件
data - 复件.rar (64.6M, 2021年3月30日 19:59 到期)
下载)

I'm sorry but the link is not working. It is only a text and is not clickable.

**Comment by drhuangliwei** [comment]
Is it right this time. if your email address can not  receive the attachment, can you give another email address？
















在 2021-03-15 20:58:45，"ahmad-ra" ***@***.***> 写道：

I believe this is the attachment for the data right? ( 从网易163邮箱发来的超大附件
data - 复件.rar (64.6M, 2021年3月30日 19:59 到期)
下载)

I'm sorry but the link is not working. It is only a text and is not clickable.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的超大附件
data - 复件(1).rar (64.6M, 2021年4月4日 9:09 到期)
下载

**Comment by shending** [comment]
hello
Could you please send me the same data?thank you very much

**Comment by drhuangliwei** [comment]
ok, no problems










At 2021-03-21 09:46:36, "XX" ***@***.***> wrote:

hello
Could you please send me the same data?thank you very much

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的超大附件
data.rar (64.6M, 2021年4月5日 20:57 到期)
下载
